package xyz.sevive.pdfimex.core

import java.util.ArrayDeque
import kotlin.time.Duration
import kotlin.time.TimeMark
import kotlin.time.TimeSource

/**
 * This class is generated by Google Gemini.
 */
class SmoothingEtaEstimator(private val windowSize: Int = 20) {
    private val durations = ArrayDeque<Duration>(windowSize)
    private var lastMark: TimeMark? = null

    /**
     * 开始计时或重置
     */
    fun start() {
        lastMark = TimeSource.Monotonic.markNow()
        durations.clear()
    }

    /**
     * 记录一步操作的耗时
     */
    fun recordStep() {
        val currentMark = TimeSource.Monotonic.markNow()
        lastMark?.let { mark ->
            // 计算自上次记录以来的耗时
            val elapsed = mark.elapsedNow()
            if (durations.size >= windowSize) {
                durations.removeFirst()
            }
            durations.addLast(elapsed)
        }
        lastMark = currentMark
    }

    /**
     * 计算预计剩余时间
     */
    fun getRemainingTime(remainingItems: Int): Duration? {
        if (durations.isEmpty() || remainingItems <= 0) return null

        // 计算平均 Duration
        val totalDuration = durations.reduce { acc, duration -> acc + duration }
        val avgDuration = totalDuration / durations.size

        return avgDuration * remainingItems
    }
}