name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  general:
    name: General Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: basic

      - name: Grant Execute Permission to Gradlew
        run: chmod +x ./gradlew

      - name: Run General Checks
        run: ./gradlew check
